<?php

namespace DoctrineProxies\__CG__\Billing\Domain\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CouponEntity extends \Billing\Domain\Entities\CouponEntity implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'amount' => [parent::class, 'amount', null, 16],
        "\0".parent::class."\0".'billingCycle' => [parent::class, 'billingCycle', null, 16],
        "\0".parent::class."\0".'code' => [parent::class, 'code', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'cycleCount' => [parent::class, 'cycleCount', null, 16],
        "\0".parent::class."\0".'deletedAt' => [parent::class, 'deletedAt', null, 16],
        "\0".parent::class."\0".'discountType' => [parent::class, 'discountType', null, 16],
        "\0".parent::class."\0".'expiresAt' => [parent::class, 'expiresAt', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'orders' => [parent::class, 'orders', null, 16],
        "\0".parent::class."\0".'plan' => [parent::class, 'plan', null, 16],
        "\0".parent::class."\0".'redemptionLimit' => [parent::class, 'redemptionLimit', null, 16],
        "\0".parent::class."\0".'startsAt' => [parent::class, 'startsAt', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'amount' => [parent::class, 'amount', null, 16],
        'billingCycle' => [parent::class, 'billingCycle', null, 16],
        'code' => [parent::class, 'code', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'cycleCount' => [parent::class, 'cycleCount', null, 16],
        'deletedAt' => [parent::class, 'deletedAt', null, 16],
        'discountType' => [parent::class, 'discountType', null, 16],
        'expiresAt' => [parent::class, 'expiresAt', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'orders' => [parent::class, 'orders', null, 16],
        'plan' => [parent::class, 'plan', null, 16],
        'redemptionLimit' => [parent::class, 'redemptionLimit', null, 16],
        'startsAt' => [parent::class, 'startsAt', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'title' => [parent::class, 'title', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
