<?php

namespace DoctrineProxies\__CG__\Billing\Domain\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OrderEntity extends \Billing\Domain\Entities\OrderEntity implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'coupon' => [parent::class, 'coupon', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'currencyCode' => [parent::class, 'currencyCode', null, 16],
        "\0".parent::class."\0".'externalId' => [parent::class, 'externalId', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'paymentGateway' => [parent::class, 'paymentGateway', null, 16],
        "\0".parent::class."\0".'plan' => [parent::class, 'plan', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'subscription' => [parent::class, 'subscription', null, 16],
        "\0".parent::class."\0".'trialPeriodDays' => [parent::class, 'trialPeriodDays', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'workspace' => [parent::class, 'workspace', null, 16],
        'coupon' => [parent::class, 'coupon', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'currencyCode' => [parent::class, 'currencyCode', null, 16],
        'externalId' => [parent::class, 'externalId', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'paymentGateway' => [parent::class, 'paymentGateway', null, 16],
        'plan' => [parent::class, 'plan', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'subscription' => [parent::class, 'subscription', null, 16],
        'trialPeriodDays' => [parent::class, 'trialPeriodDays', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'workspace' => [parent::class, 'workspace', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
